In [ ]:
import pandas as pd
from google.colab import files
import datetime
import numpy as np
import calendar

hoje = datetime.datetime.now()

In [ ]:
################ IMPORTANTE ################
# Importar a Base de dados de cada obra
# Rodar o Script uma vez para cada OBRA, ind
############################################

In [ ]:
nomeBase = input("Digite exatamente o nome do arquivo base e a sua extensão: (ex: base.xlsx)") #"2023_2_BRACELL.xlsx" # testee base.xlsx)ITAQUÍ.xlsx

Digite exatamente o nome do arquivo base e a sua extensão: (ex: base.xlsx)VIADUTO.xlsm

In [ ]:
####################### IMPORTANTE #######################
# Verficar o nome da Sheet que contém os dadaos da base.
# Verificar se é necessário SKIP ROWS
# Verificar nome das Colunas "DT Emissao" e "DT Emissao.1"

bracellBase = pd.read_excel(nomeBase, sheet_name="1-Pedidos de Compra", skiprows=1) ####, index_col=False)
#dfBracell = pd.DataFrame(bracellBase, columns =["Documento", "Razao Social", "DT Emissao PC", "DT Emissao NF", "Unidade"])
dfBracell = pd.DataFrame(bracellBase, columns =["Documento", "Razao Social", "DT Emissao.1", "DT Emissao", "Unidade"])

#display(dfBracell)#.dtypes)

In [ ]:
#bracellTable = dfBracell.groupby(["Documento", "Razao Social", "DT Emissao PC", "DT Emissao NF"], as_index=False)["Unidade"].count()
bracellTable = dfBracell.groupby(["Documento", "Razao Social", "DT Emissao.1", "DT Emissao"], as_index=False)["Unidade"].count()
bracellTable = pd.DataFrame(bracellTable).drop(columns="Unidade") #bracellTable.rename(columns={"Unidade": "Quantidade Produtos"}, inplace=True)
#display(bracellTable)

In [ ]:
### ADD AND CALCULATE COLUMN DIFERENÇA
bracellTable["DIFERENÇA"] = (bracellTable["DT Emissao.1"] - bracellTable["DT Emissao"]) / np.timedelta64(1, "D")
#bracellTable["DIFERENÇA"] = (bracellTable["DT Emissao PC"] - bracellTable["DT Emissao NF"]) / np.timedelta64(1, "D") #.map(lambda x: x[:-5])# / np.timedelta64(1, "D")
#display(bracellTable)

### ADD AND CALCULATE COLUMN REGULARIDADE
regularidadeCalc = []
for linha in bracellTable["DIFERENÇA"]:
  if linha > 0 : regularidadeCalc.append("IRREGULAR")
  else: regularidadeCalc.append("REGULAR")
bracellTable["REGULARIDADE"] = regularidadeCalc

display(bracellTable) #pd.DataFrame(bracellTable, columns = ["Documento"]))

,Documento,Razao Social,DT Emissao.1,DT Emissao,DIFERENÇA,REGULARIDADE
0,002,CECILIA RUEFF,2023-03-01,2023-03-02,-1.0,REGULAR
1,003,ANTONIO TAVARES CAMPOS,2023-03-03,2023-03-03,0.0,REGULAR
2,003,AUGUSTO BESSAS AREOSA,2023-03-03,2023-03-03,0.0,REGULAR
3,003,CECILIA RUEFF,2023-03-17,2023-03-20,-3.0,REGULAR
4,003,CRED LITORAL MEDICINA E SEGURANCA DO TRABALHO ...,2023-03-22,2023-03-24,-2.0,REGULAR
...,...,...,...,...,...,...
302,97946,"ACA INDUSTRIA, COMERCIO E CONSTRUCAO LTDA",2023-01-04,2023-02-01,-28.0,REGULAR
303,97975,"ACA INDUSTRIA, COMERCIO E CONSTRUCAO LTDA",2023-01-24,2023-02-01,-8.0,REGULAR
304,98471,"ACA INDUSTRIA, COMERCIO E CONSTRUCAO LTDA",2023-01-17,2023-03-01,-43.0,REGULAR
305,993,ALFA PRINT SINALIZACAO E COMUNICACAO VISUAL LTDA,2023-02-15,2023-03-07,-20.0,REGULAR
306,995,ALFA PRINT SINALIZACAO E COMUNICACAO VISUAL LTDA,2023-02-04,2023-03-07,-31.0,REGULAR

In [ ]:
resultado1 = bracellTable.groupby("REGULARIDADE")["REGULARIDADE"].count()
result_edit = (dict(resultado1))

regularPercent = 0 if "REGULAR" not in result_edit else (result_edit["REGULAR"]/sum(result_edit.values()))
#regularPercent = result_edit["REGULAR"]/sum(result_edit.values())
irregularPercent = 0 if "IRREGULAR" not in result_edit else (result_edit["IRREGULAR"]/sum(result_edit.values()))
#irregularPercent = result_edit["IRREGULAR"]/sum(result_edit.values())

############ Resultado Final ############
print(f'{nomeBase[:-5].upper()}\n{calendar.month_name[hoje.month]}')
print(pd.DataFrame(resultado1))
print(f'Total                  {sum(bracellTable.groupby("REGULARIDADE")["REGULARIDADE"].count())}')
#display([{"IRREGULAR": "{:.0%}".format(irregularPercent)}, {"REGULAR": "{:.0%}".format(regularPercent)}])
print("IRREGULAR {:.0%}  REGULAR {:.0%}".format(irregularPercent, regularPercent))

VIADUTO
March
              REGULARIDADE
REGULARIDADE
IRREGULAR                3
REGULAR                304
Total                  307
IRREGULAR 1%  REGULAR 99%